### ISSUE TITLE
Consider Merging with External Secrets

### ISSUE THREAD

**Issue by gusfcarvalho** [hashicorp/vault-secrets-operator#120]
**Is your feature request related to a problem? Please describe.**
this operator is very close to what external-secrets operator  (https://external-secrets.io) is doing - both supporting multiple authentication and dynamic secrets.

**Describe the solution you'd like**
a single operator that the whole community can benefit from.

**Comment by benashz** [comment]
Thank you for your interest in the vault-secrets-operator. We certainly appreciate your perspective and feedback in this regard.

The VSO project is currently focused on improving the native Kubernetes experience for Vault users. Due to potential complications with maintainability, supportability, and code ownership, as well as Vault’s product complexity, we are currently focused on this specific use case. Again, we’re grateful for your enthusiasm. Thanks!
