### ISSUE TITLE
Provide vault_token on a secret

### ISSUE THREAD

**Issue by sebglon** [hashicorp/vault-secrets-operator#129]
**Is your feature request related to a problem? Please describe.**
On some app , we need a write vault access.
For that we need a `vault_token` 

**Describe the solution you'd like**
On the `VaultStaticSecret` or `VaultDynamicSecret`, add a field to inject the vault_token like the vault agent annotation `vault.hashicorp.com/agent-inject-token`

Or a new resource like the `vault_token`for terraform: https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/token

**Comment by TheLonelyGhost** [comment]
I made this mistake early on in my usage of Vault too. Tokens are intended to be like a session cookie: short-lived authorizations. Generally you would want a well-factored application to authenticate using other means (perhaps native workload identity system like the OIDC one built into Kubernetes for service accounts) and keep it fresh for as long as it needs.

The reason that annotation exists on the Vault Agent annotation is because it can act as a proxy for calls to the Vault mothership. As such, your workload can just rely on Vault Agent doing the authentication stuff for it and then your workload just makes the HTTP calls to the agent, which only listens on a local loopback like 127.0.0.1 in the default Vault Agent Injector use case.

This operator is different in that there's no interactive component like the Vault Agent's proxy feature. This operator is simply listening for changes to Kubernetes resources and keeping tabs on secrets it requested as a result of those resources.

**Comment by hsimon-hashicorp** [comment]
Thanks @TheLonelyGhost! Nice to see you as always. :) @sebglon does this help answer your need/use case? Please let us know if there's more that you'd like to see. Thanks!

**Comment by sebglon** [comment]
Yes it solve issue; thanks
