### ISSUE TITLE
Vault and vault-secrets-operator does not work together as helm dependencies

### ISSUE THREAD

**Issue by mmalvik** [hashicorp/vault-secrets-operator#395]
**Describe the bug**
Using both `vault` and `vault-secrets-operator` as dependencies in a Helm chart does not work with the latest version of `vault-secrets-operator`. Upgrading from `0.1.0` to `0.3.1` the `helm template` fails, both locally and in our test cluster.

This is without any customization in the `values.yaml` file. 

Installing only `vault` or `vault-secrets-operator` as chart dependencies works fine.

**To Reproduce**
1. Clone the repo here: https://github.com/mmalvik/vault-secrets-operator-issue
2. Run `helm template .` to see that version `0.1.0` of `vault-secrets-operator` works.
3. Upgrade `vault-secrets-operator` to `0.3.1` in `Chart.yaml` and run `helm dependency update`.
4. Run `helm template .` command and it fails with error message:

`
Error: template: secrets-operator-issue/charts/vault/templates/tests/server-test.yaml:17:6: executing "secrets-operator-issue/charts/vault/templates/tests/server-test.yaml" at <include "imagePullSecrets" .>: error calling include: template: secrets-operator-issue/charts/vault-secrets-operator/templates/_helpers.tpl:140:15: executing "imagePullSecrets" at <.Values.controller.imagePullSecrets>: nil pointer evaluating interface {}.imagePullSecrets
`

I do not understand what is happening. Am I missing something obvious here? 😅 

I have tried overriding it through values:
```yaml
vault-secrets-operator:
  controller:
    imagePullSecrets: []
```

But no luck here.

**Expected behavior**
I expect `helm template` to render the templates.

**Environment**
* Kubernetes version: `1.23.8` for our test environment and `1.27.4` on local machine. 
  * Distribution or cloud vendor: VMware Tanzu in test env and Minikube locally
* vault-secrets-operator version: `0.3.1`

**Additional context**
We try to install `vault` and `vault-secrets-operator` in a GitOps fashion through ArgoCD and Helm chart dependencies.

It is ArgoCD that runs the `helm template` command that fails.

**Comment by macmiranda** [comment]
It is a weird issue. I'm not sure it is a bug on either chart though.

What the error is telling you that `secrets-operator-issue/charts/vault/templates/tests/server-test.yaml` template is failing when evaluating an include from `secrets-operator-issue/charts/vault-secrets-operator/templates/_helpers.tpl` (note the inconsistent paths) which should never happen since the Vault chart should use its own `_helpers.tpl` file. 

Because the Vault Secrets Operator `_helpers.tpl` refers to `.Values.controller.imagePullSecrets` and that value does not exist in in the Vault chart root scope, it fails.

You can confirm that hypothesis by adding the following to your `values.yaml`:

```
vault:
  controller: 
    imagePullSecrets:
      []
```

This should render the templates correctly.

**Comment by mmalvik** [comment]
Thanks for the investigation and tips @macmiranda 👍 

We found a workaround on our side avoiding using both `vault` and `vault-secrets-operator` as dependencies on our chart.

I will leave the issue open and leave it to hashicorp whether they want to close it or not.

**Comment by lee5i3** [comment]
I'm running into the same issue using this with ArgoCD, I'm having to treat them as separate charts rather than dependencies.

I am really hoping this can be fixed as I have not seen this happen in any other of my charts yet

**Comment by macmiranda** [comment]
I guess the simplest solution would be to rename the helper definition from VSO to something like `controller.imagePullSecrets` below
https://github.com/hashicorp/vault-secrets-operator/blob/5845d8abe3d96fe9b9e3b6c27d1bce6aef78e020/chart/templates/_helpers.tpl#L152

so that it doesn't conflict with Vault's own
https://github.com/hashicorp/vault-helm/blob/50f7439fb298d98a223d2fdf58ece2bad2d816bc/templates/_helpers.tpl#L1031
